#----------------------
# About section

blurb: <p>My name is Veronica Rivera and I am a second year PhD student in <a href="https://www.soe.ucsc.edu/departments/computational-media">Computational Media</a> at the University of California, Santa Cruz. I am a member of the <a href="https://tech4good.soe.ucsc.edu/#/">Tech4Good Lab</a> and am advised by <a href="https://tech4good.soe.ucsc.edu/#/david">Professor David Lee</a>. </p> <p>My research is in Human-Computer Interaction and Social Computing, focusing on large scale education and learning, employee development and the future of work. I develop and study technical systems to scale learning and how those systems might enable career pathways into industry. I am currently contributing to help build a platform that aims to teach beginning computer science students web development skills as they contribute to real-world projects. I am also working on a project using qualitative methods to understand the career goals of workers in online labor markets like Amazon Mechanical Turk, and envisioning how the platform might be designed and constructed to better serve workers' long-term career goals.</p> <p> In May 2017 I obtained a B.S in Joint Computer Science and Mathematics with a Concentration in Psychology at Harvey Mudd College, where I obtained a 4 year full-tuition President's Scholarship. During my time at Harvey Mudd College I conducted research in knot theory and computer vision.</p>

#----------------------
# Courses section
courses:
  - {title: Introduction to Programming Accelerated (CMPS 12A), semester: Fall 2018, school: UCSC, description: Graduate Teaching Assistant. I hold weekly office hours and lead lab section. I also grade exams and oversee undergraduate course tutors. <i>Course instructor--Professor Narges Norouzi</i>}
  - {title: Introduction to Programming in Java (CMPS 5J), semester: Spring 2018, school: UCSC, description: Graduate Teaching Assistant. I held weekly office hours and led lab section. Met with course instructor and other teaching assistants weekly to discuss student progress. <i>Course instructor--Professor Dustin Adams</i>}
  - {title: Introduction to Programming in Java (CMPS 5J), semester: Winter 2018, school: UCSC, description: Graduate Teaching Assistant. I held weekly office hours and led lab section. Met with course instructor and other teaching assistants weekly to discuss student progress. <i>Course instructor--Professor Dustin Adams</i>}
#----------------------

# Publications section
publications:
  -  
    type: conference 
    authors: <b>Rivera, Veronica</b>
    year: (2018) 
    title: A New Approach to Testing Children with Autism Spectrum Disorders Using Affect
    where: In <i>Proceedings of the 14th International Conference on Intelligent Tutoring Systems</i> (ITS 2018)(pp.496-498)
  -
    type: journal 
    authors: Nelson, Sam., Orrison, Michael., <b>Rivera, Veronica</b>
    year: (2017)
    title: Quantum Enhancements and Biquandle Brackets
    where: <i>The Journal of Knot Theory and its Ramifications</i>, 26(5)
  -
    type: conference 
    authors: Tenorio, D.,<b>Rivera, V</b>., Medina, J., Leondar, A., Gaumer, M., Dodds, Z
    year: (2015) 
    title: Visual Autonomy via 2D Matching in Rendered 3D Models
    where: In <i>Proceedings of the 11th International Symposium on Visual Computing</i> (ISVC 2015)(pp.373-385)
  -
    type: journal 
    authors: Nelson, Sam.,<b>Rivera, Veronica</b>
    year: (2014)
    title: Quantum Enhancements of Involutory Birack Counting Invariants
    where: <i>The Journal of Knot Theory and its Ramifications</i>, 23(7)
  



# Contact
contact-info: <p><b>Email:</b> veariver [at] ucsc.edu</p>

contact-links:
  - {contact-text: Twitter}
  - {contact-text: Linkedin}
