#----------------------
# About section

blurb: <p>My name is Veronica Rivera and I am a second year PhD student in Computational Media at the University of California, Santa Cruz. I am a member of the Assistive Sociotechnical Solutions for Individuals with Special Needs Using Technology (ASSIST) lab and am advised by Professor Sri Kurniawan.</p> <p>My research is in <b>Human-Computer Interaction, Assistive Technology, and Computer-Supported Cooperative Work.</b> I am primarily focused on creating interactive personalized technology to help students with Autism Spectrum Disorders (ASD) better learn and work collaboratively with their peers in the classroom. My research goals are two-fold. 1) I seek to better understand how students with ASD use technology and social media through interviews, observations and surveys. And 2) leverage those findings to develop engaging educational applications that help each student learn and improve. I aim to create applications that can adapt to each student's needs, so that all students with ASD using the application can recieve the maximum support and learning benefits, despite individual differences in their cognitive abilities</p> <p> In May 2017 I obtained a B.S in Joint Computer Science and Mathematics with a Concentration in Psychology at Harvey Mudd College, where I obtained a 4 year full-tuition President's Scholarship. During my time at Harvey Mudd College I conducted research in knot theory and computer vision.</p>

#----------------------
# Courses section
courses:
  - {title: Introduction to Programming Accelerated (CMPS 12A), semester: Fall 2018, school: UCSC, description: Graduate Teaching Assistant. I hold weekly office hours and lead lab section. I also grade exams and oversee undergraduate course tutors. <i>Course instructor--Professor Narges Norouzi</i>}
  - {title: Introduction to Programming in Java (CMPS 5J), semester: Spring 2018, school: UCSC, description: Graduate Teaching Assistant. I held weekly office hours and led lab section. Met with course instructor and other teaching assistants weekly to discuss student progress. <i>Course instructor--Professor Dustin Adams</i>}
  - {title: Introduction to Programming in Java (CMPS 5J), semester: Winter 2018, school: UCSC, description: Graduate Teaching Assistant. I held weekly office hours and led lab section. Met with course instructor and other teaching assistants weekly to discuss student progress. <i>Course instructor--Professor Dustin Adams</i>}
#----------------------

# Publications section
publications:
  -  
    type: conference 
    authors: <b>Rivera, Veronica</b>
    year: (2018) 
    title: A New Approach to Testing Children with Autism Spectrum Disorders Using Affect
    where: In <i>Proceedings of the 14th International Conference on Intelligent Tutoring Systems</i> (ITS 2018)(pp.496-498)
  -
    type: journal 
    authors: Nelson, Sam., Orrison, Michael., <b>Rivera, Veronica</b>
    year: (2017)
    title: Quantum Enhancements and Biquandle Brackets
    where: <i>The Journal of Knot Theory and its Ramifications</i>, 26(5)
  -
    type: conference 
    authors: Tenorio, D.,<b>Rivera, V</b>., Medina, J., Leondar, A., Gaumer, M., Dodds, Z
    year: (2015) 
    title: Visual Autonomy via 2D Matching in Rendered 3D Models
    where: In <i>Proceedings of the 11th International Symposium on Visual Computing</i> (ISVC 2015)(pp.373-385)
  -
    type: journal 
    authors: Nelson, Sam.,<b>Rivera, Veronica</b>
    year: (2014)
    title: Quantum Enhancements of Involutory Birack Counting Invariants
    where: <i>The Journal of Knot Theory and its Ramifications</i>, 23(7)
  



# Contact
contact-info: <p><b>Email:</b> veariver [at] ucsc.edu</p>

contact-links:
  - {contact-text: Twitter}
  - {contact-text: Linkedin}
