#----------------------
# About section

blurb: <p>My name is Veronica Rivera and I am a second year PhD student in Computational Media at the University of California, Santa Cruz. I am a member of the Assistive Sociotechnical Solutions for Individuals with Special Needs using technology (ASSIST) lab and am advised by Professor Sri Kurniawan. My research is in Human-Computer Interaction, Assistive Technology, Education and Computer-Supported Cooperative Work. I am primarily focused on creating interactive technology to help students with Autism Spectrum Disorders (ASD) better learn and work with their peers in the classroom. Before coming to UC Santa Cruz, I obtained a B.S in Joint Computer Science and Mathematics with a Concentration in Psychology at Harvey Mudd College, where I was a 4-year President's Scholar.</p>

#----------------------
# Courses section
courses:
  - {title: Intro to Chem, semester: Fall 1885, school: King's College London, description: Teaching students chemistry isn't only for witches., link: courses/temp_course }
  - {title: Advanced Psychiatric Medicine, semester: Spring 1885, school: King's College London, description: At the time, mainly lobotomy., link: courses/temp_course }
  - {title: Diseases of the Mind, semester: Fall 1884, school: King's College London, description: Survey course. Mainly taught by example., link: courses/temp_course }
#----------------------
# Contact
contact-info: <p>Veronica Rivera<br>veariver@ucsc.edu</p>

contact-links:
  - {contact-text: Github, contact-link: "https://www.google.com", icon: 'favicon.html'}
